services:
  landingclient:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5172:5173"
    volumes:
      - .:/app
      - landing-packages:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
volumes:
  landing-packages:
